options:
  logging: CLOUD_LOGGING_ONLY

steps:
  #Build imagen
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_CONTAINER_NAME}:$SHORT_SHA
      - .

  #Push imagen
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_CONTAINER_NAME}:$SHORT_SHA

  # Crear service.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        cat <<EOF > service.yaml
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: ${_SERVICE_NAME}
        spec:
          template:
            spec:
              containers:
                - image: ${_CONTAINER_NAME}
                  ports:
                    - containerPort: ${_CONTAINER_PORT}
        EOF

        echo "===== service.yaml ====="
        cat service.yaml


  # Crear skaffold.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        cat <<EOF > skaffold.yaml
        apiVersion: skaffold/v4beta7
        kind: Config
        metadata:
          name: ${_CONTAINER_NAME}
        build:
          artifacts: 
            - image: ${_CONTAINER_NAME}
        manifests:
          rawYaml:
            - service.yaml
        deploy:
          cloudrun: {}
        EOF

        echo "===== skaffold.yaml ====="
        cat skaffold.yaml

  #Crear release en Cloud Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - deploy
      - releases
      - create
      - release-${SHORT_SHA}
      - --delivery-pipeline=${_PIPELINE_NAME}
      - --region=${_REGION}
      - --images=${_CONTAINER_NAME}=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_CONTAINER_NAME}:$SHORT_SHA