options:
  logging: CLOUD_LOGGING_ONLY

steps:
  #Crear skaffold.yaml para despliegue
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        cat <<EOF > skaffold.yaml
        apiVersion: skaffold/v2beta26
        kind: Config
        deploy:
          cloudrun:
            serviceName: ${_SERVICE_NAME}
            region: ${_REGION}
        EOF

        echo "Contenido de skaffold.yaml:"
        cat skaffold.yaml

  #Build imagen
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_CONTAINER_NAME}:$SHORT_SHA
      - .

  #Push imagen
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_CONTAINER_NAME}:$SHORT_SHA

  #Crear release en Cloud Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - deploy
      - releases
      - create
      - release-${SHORT_SHA}
      - --delivery-pipeline=${_PIPELINE_NAME}
      - --region=${_REGION}
      - --images=app=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_CONTAINER_NAME}:$SHORT_SHA