apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
spec:
  template:
    spec:
      containers:
        - image: containerurl
          ports:
            - containerPort: ${CONTAINER_PORT}